{{- range .Values.daemons }}
{{- if .enabled }}
{{- $tls := .tls | default dict }}
{{- $server := $tls.server | default dict }}
{{- $client := $tls.client | default dict }}
{{- if and $server.enabled (not $server.existingSecret) $server.ca $server.cert $server.key }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "buildkit.tlsServerSecretName" (list $ .) }}
  labels:
    {{- include "buildkit.labels" (list $ .) | nindent 4 }}
type: Opaque
data:
  {{ ($server.secretKeys | default dict).ca | default "ca.pem" }}: {{ $server.ca }}
  {{ ($server.secretKeys | default dict).cert | default "cert.pem" }}: {{ $server.cert }}
  {{ ($server.secretKeys | default dict).key | default "key.pem" }}: {{ $server.key }}
{{- end }}
{{- if and $client.enabled (not $client.existingSecret) $client.ca $client.cert $client.key }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "buildkit.tlsClientSecretName" (list $ .) }}
  labels:
    {{- include "buildkit.labels" (list $ .) | nindent 4 }}
type: Opaque
data:
  {{ ($client.secretKeys | default dict).ca | default "ca.pem" }}: {{ $client.ca }}
  {{ ($client.secretKeys | default dict).cert | default "cert.pem" }}: {{ $client.cert }}
  {{ ($client.secretKeys | default dict).key | default "key.pem" }}: {{ $client.key }}
{{- end }}
{{- end }}
{{- end }}
