metrics:
  enabled: true

daemons:
  - name: e2e
    enabled: true
    variant: buildkit
    mode: pod
    rootless: true
    storage:
      type: emptyDir
    service:
      enabled: true
      port: 1234
    metrics: {}
    livenessProbe:
      exec:
        command:
          - buildctl
          - debug
          - workers
      initialDelaySeconds: 5
      periodSeconds: 30
      timeoutSeconds: 5
      failureThreshold: 3
    readinessProbe:
      exec:
        command:
          - buildctl
          - debug
          - workers
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 6
      successThreshold: 1
